### ISSUE TITLE
Doesn't appear to do anything.

### ISSUE THREAD

**Issue by kyoneko66** [wildbook/R2Mods#1]
The description on the mod does not seem to include a thing about where to put your file. I am guessing they go in BepInEx\plugins however.

After this i tried to use the command to up the multiplayer simulation and... Nothing. The command does return its message like normal, but no matter where i input the command, in the menu, in the character selection, in game. Neither in single player nor multiplayer does it seem to have any effect.

I even tried removing all my other mods to just have a fresh game with only this mod and that didn't seem to help either.

Either i am missing a step (in that case please include these instructions in the readme) or something is not working.

**Comment by Makeshift** [comment]
Same issue. During startup I get the following exception in BepInEx 5.0.0.0:

```
[Info   :   BepInEx] Loading [Multitudes 1.3.0]
[Error  : Unity Log] KeyNotFoundException: The given key was not present in the dictionary.
Stack trace:
MonoMod.Cil.ILCursor.GotoNext (MonoMod.Cil.MoveType moveType, System.Func`2[Mono.Cecil.Cil.Instruction,System.Boolean][] predicates) (at <9f5e5b1e932c4b10bb604114932729d8>:0)
MonoMod.Cil.ILCursor.GotoNext (System.Func`2[Mono.Cecil.Cil.Instruction,System.Boolean][] predicates) (at <9f5e5b1e932c4b10bb604114932729d8>:0)
Multitudes.Multitudes.<Awake>b__7_1 (MonoMod.Cil.ILContext il) (at <d7adaf73cea84a17aa25fa48a90480df>:0)
MonoMod.Cil.ILContext.Invoke (MonoMod.Cil.ILContext+Manipulator manip) (at <9f5e5b1e932c4b10bb604114932729d8>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint.InvokeManipulator (Mono.Cecil.MethodDefinition def, System.Delegate cb) (at <24f82f85fb084b2fb4ddfb2e7c8f8303>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify (System.Delegate callback) (at <24f82f85fb084b2fb4ddfb2e7c8f8303>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify (System.Reflection.MethodBase method, System.Delegate callback) (at <24f82f85fb084b2fb4ddfb2e7c8f8303>:0)
MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T] (System.Reflection.MethodBase method, System.Delegate callback) (at <24f82f85fb084b2fb4ddfb2e7c8f8303>:0)
IL.RoR2.Run.add_FixedUpdate (MonoMod.Cil.ILContext+Manipulator ) (at <bf17a362ebf74a0091fc8306207c4bba>:0)
Multitudes.Multitudes.Awake () (at <d7adaf73cea84a17aa25fa48a90480df>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()
```

I have no other mods installed other than the R2API. Oddly, my boyfriend with the exact same setup as me is NOT getting this problem, so I'm not entirely sure what's up.

The message returns as expected when typed in the console, but doesn't actually work.

I hooked up the dnSpy debugger to see if I could get a bit more info out of the exception, but I'm not super familiar with .net debugging so if there's anything I can do to help let me know.

**Comment by wildbook** [comment]
@kyoneko66 Yeah, all mods go in there if nothing else is specified, my bad. As for your issue, are you sure you're using mod_wb_**set**_multiplier and not mod_wb_**get**_multiplier?

@Makeshift You most likely have files from SeikoML left over, it looks like the crash you'd usually get from that. If so, remove your RoR2 directory manually and reinstall the game by validating files in Steam's UI, then try again from there. Make sure you got everything updated, RoR2 / Multitudes / BepInEx.

**Comment by kyoneko66** [comment]
Yes, i am using the set option, i even for the heck of it tried to use the get to set it (which obviously doesn't work but who knows). Whenever i use the set option with 100 i do get back the message "Multiplier set to 100. Good luck!" But when i get in game after that nothing special happens, chests still cost 25, chests and enemies are sparse, just normal single player gameplay. I tried it with a full reinstall, varifying files, moving my steam folder from my D drive to C/program files(x86). None of that all makes a diffrence.

**Comment by wildbook** [comment]
There isn't really any steps to miss, so I can't say I know what'd cause it. Any errors in either of the console windows?

**Comment by kyoneko66** [comment]
Right, the console still exists.. It acually gives the exact same message as @Makeshift has copied over. I never had SeikoML installed, and even on a fresh instalation i have the issue.

**Comment by wildbook** [comment]
After looking at it a bit more, it still really looks like old leftover files loading over new ones.

Did you reinstall the game through Steam, or delete the game folder manually? If the former, Steam only removes files it placed in the game folder, so older mods/modloaders/etc. will still be left there to interfere with a fresh installation.

**Comment by kyoneko66** [comment]
I have removed it via steam, removed the remains, reinstalled it, even tried uninstalling it from D and installing it fresh onto C. Dunno why but today it seems to suddenly start working. Didn't change a thing since yesterday.

**Comment by wildbook** [comment]
Nice to have it resolved either way. I'm closing the issue, but if you find more information about what caused it, feel free to comment on here for others to find.
