### ISSUE TITLE
TooManyFriends not working with BepInExPack mod loader 3.0.0, 3.20  or 3.2.0

### ISSUE THREAD

**Issue by SebastianTroy** [wildbook/R2Mods#15]
Appears that the 3.x.x BepInExPack mod loader has removed a dependancy for the TooManyFriends mod, the following is the output from the 3.0.0 version I tested, the same "missing dependencies: com.bepis.r2api" message is also present for 3.1.0 and 3.2.0

[Message:   BepInEx] BepInEx 5.0.1.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher methods from BepInEx.MonoMod.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Info   :   BepInEx] 2 patcher plugin(s) loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   MonoMod] Collecting target assemblies from mods
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Error  :   BepInEx] Could not load [TooManyFriends] because it has missing dependencies: com.bepis.r2api
[Message:   BepInEx] Chainloader startup complete
Setting breakpad minidump AppID = 632360
Steam_SetMinidumpSteamID:  Caching Steam ID:  [API loaded no]

**Comment by NeshZul** [comment]
You should install this 
[https://thunderstore.io/package/tristanmcpherson/R2API/](url)

**Comment by wildbook** [comment]
Added R2API as a listed dependency now, took me long enough.
