### ISSUE TITLE
Multitudes Causes Final Boss to Never Start Fight

### ISSUE THREAD

**Issue by VaelophisNyx** [wildbook/R2Mods#17]
/title.

the fake players cause the game to wait on players who don't exist to start the fight

**Comment by VaelophisNyx** [comment]
After testing this with the new update for this mod; it seems to still be a problem.

**Comment by wildbook** [comment]
That makes sense, the update more or less only fixed API changes/incompatibilities. I'll try to get that fixed once I get some time left over, for now I'm not sure where in the game the logic I'd need to modify is. Thanks for the heads up.

**Comment by Sakhanist** [comment]
You can switch back to 1player, run to the barrier wall, then run into the arena as a small fix. Worked for me.

**Comment by wildbook** [comment]
Should be fixed now.
