### ISSUE TITLE
TooManyFriends : the supplementary players can't get in the lobby

### ISSUE THREAD

**Issue by Linkoura** [wildbook/R2Mods#21]
Despite all of us being able to see the supplementary lobby slots (up to 16) and being able to try to invite another player, it seems like when the fifth player tries to join he gets put in a new lobby by himself instead of joining the rest. Not sure if it has to do with the latest update of the game or we missed something.

**Comment by closerex** [comment]
> Despite all of us being able to see the supplementary lobby slots (up to 16) and being able to try to invite another player, it seems like when the fifth player tries to join he gets put in a new lobby by himself instead of joining the rest. Not sure if it has to do with the latest update of the game or we missed something.

Same here, This mod seems to be incompatible with R2API newer than 2.4.29.

**Comment by wildbook** [comment]
Should be fixed now.
