### ISSUE TITLE
Readme is lacking

### ISSUE THREAD

**Issue by TrogdorTheMan** [wildbook/R2Mods#23]
Please include some instructions on your readme, like where to actually put the plugin when installing manually. Even just a few scentences would have been helpful.

**Comment by TrogdorTheMan** [comment]
Also found we had to install R2API v2.5.6 to get the mod working even with bepinex

https://thunderstore.io/package/tristanmcpherson/R2API/

**Comment by TrogdorTheMan** [comment]
I actually see its been added in other issues. Sorry!

**Comment by wildbook** [comment]
No problem at all. When I first published it R2API wasn't a separate dependency but shipped with BepInEx and the other tools required, then when it eventually split I forgot to add it. Fixed now.

As for a better readme, I'll see if I can write one up when I get some spare time.
