### ISSUE TITLE
Overabundance of yellow items spawn after defeating boss

### ISSUE THREAD

**Issue by zgurwitz** [wildbook/R2Mods#25]
I've been playing 4x7 and  at least 24 of the items dropped by boss are consistently yellow

**Comment by wildbook** [comment]
Sorry for the uh, 9 months delay. I'm just now going through issues again. Multitudes doesn't change anything when it comes to spawnrates, it just makes the game believe there are more players, so any effects like these are almost certainly just due to how the game handles more players in general.
