### ISSUE TITLE
Forces isModded to true

### ISSUE THREAD

**Issue by grundyboy34** [wildbook/R2Mods#3]
This mod seems to force isModded to become true. Installing BebInEx with modded set to false allows the game to connect to other non-modded users, as do other BebInEx plugins, but adding this one sets the modded state and I can then no longer connect with friends who don't want to download mods.

**Comment by wildbook** [comment]
Anything that changes lobby size will force IsModded to true, as the game itself checks for a lobby size != 4 and sets the flag.

I could work around it, and I might do so in the future, but for now it's caused by RoR2's developers flagging you for your non-default lobby size.

**Comment by grundyboy34** [comment]
Ahh okay, I wasn't aware that was a thing. I'd been using Loot16All before which I'm guessing does a work around. Thanks!

**Comment by wildbook** [comment]
No problem!
