### ISSUE TITLE
Multitudes increases difficulty but not loot

### ISSUE THREAD

**Issue by tjansie** [wildbook/R2Mods#30]
Hi, new to modding ROR2

When using multitudes, it increases the difficulty, chests cost more etc, but the loot stays the same. Browsed the web, tried reïnstalling etc but didn't fix anything.

Thanks for responses in advance!

**Comment by wildbook** [comment]
Hi, sorry for the delay. Multitudes works by just straight up tricking the game there are more players than there actually are, so any scaling issues or things like these will be up to the game to handle.

I could in theory override the logic and write my own for things like loot, but right now I just let the game handle it as if there were actually just that many players on the map.

I don't *think* it's bugged but rather just how RoR2 does things, but I actually don't know. If it's a bug in Multitudes I wouldn't mind fixing it, so just reopen the issue if you're sure that's it.

**Comment by Kithio** [comment]
A known collision is ShareSuite, it has its own item scaling change that can be disabled in the config file of ShareSuite, if you're running with that mod, I recommend looking at that
