### ISSUE TITLE
Multitudes - not working in multiplayer?

### ISSUE THREAD

**Issue by xal3xhx** [wildbook/R2Mods#4]
i started a game with a friend and had player count set high and it appears that nothing happens. im amusing the mod is happy working in multiplayer??

**Comment by wildbook** [comment]
Assuming the host is the one with Multitudes, it should work flawlessly in multiplayer.
If nothing happens when the host has Multitudes installed, please post screenshots of your BepInEx and in-game consoles, and I'll try to find why it doesn't work.

**Comment by nssophia** [comment]
when we open the teleporter,there was no boss,idk if it was normal or just me ,MultitudesX4 ,in multiplayer
