### ISSUE TITLE
Publicize modGUID

### ISSUE THREAD

**Issue by harbingerofme** [wildbook/R2Mods#9]
https://github.com/wildbook/R2Mods/blob/e13bac0fd10f66153cc60e7cd8d41ab3d74aec59/MiniRpcLib/MiniRpcLib.cs#L14
Please make this public to help referencing as dependency

**Comment by wildbook** [comment]
Anything against using this? I almost pushed an update to make it public but realized this one exists.
 https://github.com/wildbook/R2Mods/blob/develop/MiniRpcLib/MiniRpcLib.cs#L10

**Comment by harbingerofme** [comment]
No, I missed it. My bad.
